[package]
name = "dungeons_and_dragons"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rustyline = "10.0.0"
rand_chacha = "0.3.1"